//! Shared behavioral fixtures: where the oracle's capture is, whether it is
//! there, and how the suites that read it read it.
//!
//! # Why this is a crate and not three copies
//!
//! Three suites read the same capture — the wire crate's layout tests, the
//! protocol/model tests, and the device's decoder tests — and each carried its
//! own `fixtures()`, its own `unhex()`, and its own spelling of where the files
//! live. Two of the three wrote the directory as
//! `{manifest}/../reims-vgpu-wire/fixtures` and one as `{manifest}/fixtures`,
//! which is the same directory only as long as nobody moves a crate.
//!
//! The presence probe was already shared, by `include!`-ing one file from three
//! build scripts, with a comment arguing that a build-dependency crate for
//! twenty lines would cost more than it carries. That was true while twenty
//! lines was all there was to share. It is not true now: the loaders and the
//! hex helper go with it, so the crate carries the whole of "how a suite reaches
//! the capture" rather than one clause of it, and `include!` across a directory
//! boundary stops being the mechanism.
//!
//! # Presence is a build-time fact
//!
//! [`probe_wire_fixtures`] emits `wire_fixtures` and `wire_inventory` so a test
//! can carry `#[cfg_attr(not(wire_fixtures), ignore = "…")]` and libtest can
//! print `ignored` for each one. The arrangement that replaced returned early
//! inside each test body, so tests that measured nothing reported `ok` in
//! 0.00 s — the only layout-truth tests in the project, reading exactly like
//! coverage on every checkout without the capture.
//!
//! Anything that goes wrong in a *loader* is therefore the capture being
//! removed between building a test and running it, not the ordinary
//! fixture-less checkout, and the panics say so.
//!
//! # And the instruments a suite measures with
//!
//! The capture is one shared fixture; [`allocations`] and [`obligations`] are
//! two more. All three are
//! things several suites need and none of them owns, and a second copy of a
//! `GlobalAlloc` is a second thing to get subtly wrong — the same argument
//! that put the loaders here rather than in three crates.

pub mod allocations;
pub mod dispatch;
pub mod obligations;
pub mod slugs;

use serde_json::Value;

/// The directory the capture lives in.
///
/// One answer for every suite. `CARGO_MANIFEST_DIR` here is this crate's, so
/// the relative path is fixed rather than re-derived from wherever the caller
/// happens to sit.
#[must_use]
pub fn fixtures_dir() -> String {
    reims_vgpu_config::wire_fixtures_dir()
        .unwrap_or_else(|| format!("{}/../reims-vgpu-wire/fixtures", env!("CARGO_MANIFEST_DIR")))
}

/// Apple's captured records.
///
/// # Panics
///
/// If the file is missing or malformed. `build.rs` already decided it exists —
/// every caller sits behind the `cfg` that decision sets — so a failure here is
/// the capture being removed mid-run.
#[must_use]
pub fn fixtures() -> Value {
    oracle_output("fixtures.json", "")
}

/// The oracle's selector inventory.
///
/// # Panics
///
/// As [`fixtures`].
#[must_use]
pub fn inventory() -> Value {
    oracle_output("inventory.json", " --inventory")
}

/// Read one of the oracle's outputs, or say what regenerates it.
///
/// # Panics
///
/// As [`fixtures`].
#[must_use]
pub fn oracle_output(file: &str, regenerate_args: &str) -> Value {
    let dir = fixtures_dir();
    let path = format!("{dir}/{file}");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{path} was present when this test was built and is not now ({e}); \
             regenerate with scripts/wire-oracle/wire-oracle.sh{regenerate_args}"
        )
    });
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{path} is not valid JSON: {e}"))
}

/// The bytes behind a fixture's hex string.
///
/// # Panics
///
/// On an odd length or a non-hex digit. A capture that spells a buffer wrong is
/// a capture to regenerate, not one to read half of.
#[must_use]
pub fn unhex(hex: &str) -> Vec<u8> {
    assert!(hex.len().is_multiple_of(2), "hex buffer has an odd length");
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex digit"))
        .collect()
}

/// Emit `wire_fixtures` and `wire_inventory` for whichever oracle outputs
/// exist. Call from a build script.
///
/// The two outputs are probed separately so a stale capture is distinguishable
/// from a missing one: `inventory.json` is regenerated by
/// `wire-oracle.sh --inventory` and `fixtures.json` by the sweep, and having one
/// without the other is a normal intermediate state that should stand down only
/// the tests that read the absent half.
///
/// # Panics
///
/// If `REIMS_WIRE_FIXTURES_REQUIRED` is set and an output is missing. The
/// runtime assertion this replaces cannot fire any more — an ignored test never
/// runs to check it — so failing the build is what keeps `REQUIRED` meaning
/// "these must have run".
pub fn probe_wire_fixtures(default_dir: &str) {
    println!("cargo:rerun-if-env-changed=REIMS_WIRE_FIXTURES_DIR");
    println!("cargo:rerun-if-env-changed=REIMS_WIRE_FIXTURES_REQUIRED");
    println!("cargo:rustc-check-cfg=cfg(wire_fixtures)");
    println!("cargo:rustc-check-cfg=cfg(wire_inventory)");

    let dir = reims_vgpu_config::wire_fixtures_dir().unwrap_or_else(|| default_dir.to_string());
    let required = reims_vgpu_config::wire_fixtures_required();

    let mut absent = false;

    for (file, cfg) in [
        ("fixtures.json", "wire_fixtures"),
        ("inventory.json", "wire_inventory"),
    ] {
        let path = format!("{dir}/{file}");
        if std::path::Path::new(&path).is_file() {
            println!("cargo:rerun-if-changed={path}");
            println!("cargo:rustc-cfg={cfg}");
        } else if required {
            panic!(
                "REIMS_WIRE_FIXTURES_REQUIRED is set but there is no {file} at \
                 {dir}; regenerate with scripts/wire-oracle/wire-oracle.sh"
            );
        } else {
            absent = true;
        }
    }

    if absent {
        // Watch the *containing directory* for the outputs that are not there
        // yet, never the absent file by name. Cargo cannot stat a missing
        // watched path, reads that as changed, and so marks the build script
        // dirty on every single build — and since a dependent's fingerprint
        // includes its build script's, naming an absent file here recompiled
        // every consumer on every invocation on every checkout without the
        // capture, which is every non-Apple one. A directory's recorded mtime
        // moves when a file is created inside it, so watching the nearest one
        // that exists keeps the property the by-name watch was for: a capture
        // taken after a build is picked up without a manual touch. Climb at
        // most one level, so a `REIMS_WIRE_FIXTURES_DIR` pointing into a tree
        // that does not exist watches nothing rather than walking some huge
        // ancestor.
        let dir = std::path::Path::new(&dir);
        let watch = if dir.is_dir() {
            Some(dir)
        } else {
            dir.parent().filter(|parent| parent.is_dir())
        };
        if let Some(watch) = watch {
            println!("cargo:rerun-if-changed={}", watch.display());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_reads_a_buffer_the_capture_spells() {
        assert_eq!(unhex(""), Vec::<u8>::new());
        assert_eq!(unhex("00ff10"), vec![0x00, 0xff, 0x10]);
    }

    #[test]
    #[should_panic(expected = "odd length")]
    fn an_odd_hex_length_is_a_capture_to_regenerate() {
        let _ = unhex("abc");
    }

    /// One answer for every suite, whichever crate is asking.
    #[test]
    fn the_capture_directory_is_one_path_and_not_three() {
        let dir = fixtures_dir();
        assert!(
            dir.ends_with("/fixtures"),
            "the capture directory is a `fixtures` directory: {dir}"
        );
    }
}
